name: Lint
on:
  pull_request:
    branches:
      - master
      - next
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup node/npm
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: npm --no-workspaces ci

      - name: Lint
        run: npm run lint
